Set Shell zsh
Set Padding 20
Set BorderRadius 10
Set Width 1250
Set Height 400
Output demo.gif

Sleep 1.5s
Backspace
Type "./rejoinderoo"
Enter
Sleep 1s
Down
Sleep 0.5s
Enter
Sleep 0.5s
Space
Sleep 0.5s
Down
Sleep 0.5s
Space
Sleep 0.5s
Down
Sleep 0.5s
Space
Sleep 0.5s
Down
Sleep 0.5s
Space
Sleep 1s
Enter
Sleep 1s
Down
Sleep 1s
Up
Sleep 1s
Enter
Sleep 0.5s
Type "rejoinder.tex"
Sleep 1.5s
Enter
Sleep 5s
